In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
tr = pd.read_csv('C:/Users/Nikhil/Downloads/train.csv')
tr

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
tr.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [20]:
y = tr[['SalePrice']]
x = tr[['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']]

In [4]:
from sklearn.model_selection import train_test_split

In [81]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [84]:
from sklearn.tree import DecisionTreeRegressor

In [16]:
dr = DecisionTreeRegressor()

In [20]:
dr.fit(x,y)

DecisionTreeRegressor()

In [24]:
y_predict = dr.predict(x.head())
y_predict

array([208500., 181500., 223500., 140000., 250000.])

In [25]:
dr = DecisionTreeRegressor(random_state=1)

In [26]:
dr.fit(x_train,y_train)

DecisionTreeRegressor(random_state=1)

In [31]:
y_predict=dr.predict(x_test)
y_predict

array([335000., 205000., 124000., 205000.,  89500.,  58500., 350000.,
       113000., 755000., 147576., 213500., 150900., 210000., 125500.,
       142125., 153000., 236000., 126000., 151000., 128000., 135000.,
       149000.,  62383., 185000., 139000., 138887., 195000.,  92000.,
       326000., 105500., 118000., 196500.,  99500., 258000., 377500.,
       168500., 234000., 111250., 222500., 315750., 244000., 130000.,
       185500., 236500., 267000., 125000., 107500., 144000., 179900.,
       128500., 315750., 154500., 196000., 113000., 193000., 120500.,
       153575., 190000.,  93000.,  87000., 126500., 150000., 140000.,
       141000., 262000., 144500., 129000., 210000., 107400., 208500.,
       189000., 142125., 139000., 250580., 135750., 284000., 131500.,
        76000., 325300., 161500., 143000., 134900.,  58500., 147000.,
       274970., 176000.,  79000., 202500., 198900., 109000., 216000.,
       130500., 175500., 238000., 206000.,  60000., 190000., 274970.,
       120500., 137450., 318000., 248000., 162000., 149500.,  79900.,
       250000., 156000., 119750., 184000., 128000.,  81000., 132000.,
       226000.,  95000., 176000., 146000., 466500., 132000., 195000.,
       252000., 149000., 176000., 131500., 205000., 236500., 265900.,
       423000., 185000., 197000., 218000., 173000., 185000., 154300.,
       175500., 120500., 224900., 105000., 176000., 116500., 178000.,
       135000., 148000., 335000., 155000., 145000., 175500., 350000.,
       109000., 318061., 208900., 167000., 147000., 372402., 133900.,
       127000., 200000., 123500., 140000., 157000., 178000., 120500.,
       150000., 167500., 108000., 220000., 154900., 139900., 337000.,
       185850., 172400., 149900., 197000., 207500., 118500., 223500.,
       122900., 123500., 272000., 105000., 153500., 196000., 184000.,
        34900., 318000., 105000., 174500., 113000., 185850., 196000.,
       149000., 126000., 121500., 214000., 140000.,  58500., 156000.,
        75500., 142000., 167900., 151000., 153000., 190000.,  72500.,
       148500., 128000., 240000., 151000., 226000., 312500.,  58500.,
       155000., 213000.,  93500.,  91000., 287000., 169000., 171500.,
       250000., 284000.,  92000., 175000., 175000., 135900., 111250.,
       191000., 219500., 177500., 287000., 126175., 218000.,  93500.,
        95000., 120500., 147000., 231500., 133000., 139000., 120500.,
       123500., 175000., 121600., 173000., 231500., 235000., 143500.,
       112000., 118911., 173000., 105000., 176000., 137500., 281000.,
       115000., 424870., 198900., 311872., 135000., 174000., 184750.,
       556581., 130000., 164000., 160000., 163000., 440000., 395192.,
       144000.,  89000., 189000., 248328., 149000., 158000., 149000.,
       215000., 130000., 274725., 194500., 140000., 274725., 153900.,
       130000., 423000., 140000., 150000., 220000., 244000.,  94500.,
       147000., 501837., 259500.,  80000.,  37900., 326000., 142000.,
        64500., 312500., 220000., 185850., 155000., 160000., 100000.,
       115000., 179665., 185850., 164000., 121500., 140000., 170000.,
       155835., 180000., 109900., 164500., 145000., 102776., 105000.,
       142000., 226000., 153000., 171750., 225000., 102000., 213000.,
       105000., 226000., 106000., 252000., 122000., 394432., 160000.,
       143000., 128500., 275000., 179500., 169990., 170000., 146800.,
       110500., 180000., 151000., 139400., 236500., 162000., 154000.,
       274725., 175500., 149000.,  94000., 150000., 105000., 143000.,
       190000., 267000., 127500., 127500., 153500., 369900., 267000.,
       140000., 315500., 169000., 250000., 190000., 214000., 220000.,
       109500.,  90000., 178000., 117500., 269500., 167000., 426000.,
       134900., 137000., 131400., 180000.,  80000., 214000., 266000.,
       111250., 225000., 113000., 117000., 189950., 115000., 119900.,
        67000., 223500., 189000., 272000., 423000.,  85500., 144900.,
       244000., 110000., 143000., 189000., 131500., 174000., 164900.,
       172400., 276000., 234000., 140000.,  92000., 107000., 339750.,
       110000., 361919., 202900., 350000., 150000., 135000., 157000.,
       130000., 170000., 106500., 215000.,  94500., 250000., 151000.,
       290000., 361919., 110000., 146000., 140000.,  88000., 244000.,
        80000., 280000., 131500., 143000., 212000., 146800., 143000.,
       167000., 257000., 234000., 582933.])

In [82]:
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [32]:
mean_absolute_error(y_test,y_predict)

32767.703196347033

In [76]:
MAE1 = []
for i in range(0,5):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leafs_nodes[i], random_state=0)
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)
    model.fit(x_train,y_train)
    preds_val = model.predict(x_test)
    MAE = mean_absolute_error(y_test, preds_val)
    MAE1.append(MAE)

In [36]:
max_leafs_nodes = [5, 25, 50, 100, 250, 500]

In [73]:
max_leafs_nodes[0]

5

In [77]:
MAE1

[34835.49253249091,
 28100.092926645324,
 28522.12328974183,
 29695.55176545459,
 31834.79264590686]

In [115]:
from sklearn.ensemble import RandomForestRegressor

In [69]:
rf = RandomForestRegressor(random_state=1)

In [70]:
rf.fit(x_train,y_train)

RandomForestRegressor(random_state=1)

In [71]:
rf_predict = rf.predict(x_test)
rf_predict

array([279125.        , 161878.68      , 121501.64      , 194837.        ,
        88203.        ,  85494.93      , 240796.95      , 124602.59      ,
       625507.33      , 169941.28266667, 200164.8       , 154883.916     ,
       229488.35      , 123700.        , 135808.25      , 135057.        ,
       237219.6       , 133214.        , 150386.87      , 129147.71      ,
       126116.18      , 146153.33333333, 107214.86      , 183427.31      ,
       157838.5       , 153147.88      , 176983.        ,  88502.        ,
       325057.37      , 106243.02      , 139285.        , 190615.        ,
       123536.625     , 284773.63      , 363412.17      , 180438.75      ,
       223716.83      , 115481.5       , 224282.78      , 295766.01      ,
       220652.        , 141525.75666667, 185989.76      , 295294.95      ,
       303918.83      , 142075.        , 103195.32      , 127630.5       ,
       164848.5       , 113202.75      , 318306.89      , 149584.25      ,
       162783.        , 108876.        , 239660.52      , 102616.76      ,
       120696.32      , 212811.34      , 137776.5       ,  99593.        ,
       142732.5       , 128182.51      , 139468.        , 155016.        ,
       222089.12      , 158457.        , 135732.5       , 206610.43      ,
       107116.14      , 202850.55      , 178734.92      , 121027.93      ,
       118166.15      , 217286.38      , 117703.5       , 272471.44      ,
       126869.5       ,  90739.        , 319233.74      , 151340.5       ,
       126932.125     , 122092.66      , 117231.76      , 137070.        ,
       253022.9       , 187420.09      , 107097.75      , 201189.8       ,
       198495.78      , 127905.25      , 191094.15      , 169043.9       ,
       186067.79      , 227399.5       , 178044.25      , 125985.5       ,
       214296.99      , 178185.68      , 106731.97      , 137319.754     ,
       297845.89      , 228612.35      , 152126.        , 158267.25      ,
        76916.98      , 280845.72      , 141261.5       , 109420.79      ,
       177827.8       , 120094.58      ,  70204.75      , 126812.        ,
       211212.28      , 108415.        , 173487.5       , 147938.34      ,
       407985.24      , 130591.        , 206126.82      , 248089.22      ,
       150175.        , 166075.96      , 122422.        , 197611.        ,
       233653.14      , 230111.6       , 386354.77      , 192208.81      ,
       186966.42      , 177303.5       , 192857.49      , 186172.29      ,
       180332.58      , 181532.        , 117196.65      , 247562.05      ,
       123734.        , 188761.88      , 108787.        , 186022.82      ,
       144550.57      , 149686.52      , 260874.5       , 146911.33333333,
       178659.87      , 182724.19      , 235526.62      , 131817.5       ,
       263074.03      , 211959.5       , 161488.5       , 306226.5       ,
       310590.53      , 149625.79      , 145677.25      , 218878.79      ,
       124967.        , 163652.5       , 149011.77      , 175581.        ,
       122669.99      , 148687.5       , 180613.98      , 122829.        ,
       239214.74      , 145177.52      , 152180.        , 316520.68      ,
       190359.54      , 180828.5       , 154131.82      , 149879.2       ,
       194807.88      , 163212.        , 143579.5       ,  98759.44      ,
       128555.61      , 238481.37      , 106723.02      , 150031.        ,
       197491.2       , 171161.32      ,  81174.04      , 297370.62      ,
       106772.        , 175152.        ,  85814.        , 193001.28      ,
       208328.9       , 142249.66666667, 133214.        , 135747.        ,
       223640.03      , 141960.        ,  91985.28      , 144514.5       ,
        83049.        , 141671.        , 167336.74      , 124944.4       ,
       146127.5       , 169333.2       , 100760.        , 145312.83333333,
       133920.        , 215714.9       , 150446.87      , 246168.89      ,
       289851.47      ,  75372.11      , 152519.5       , 253356.39      ,
        98147.36      ,  88699.        , 250959.54      , 224076.62      ,
       180800.5       , 276818.99      , 267629.32      ,  88600.        ,
       194706.5       , 161652.5       , 131213.62      , 118002.16      ,
       191891.86      , 234021.        , 212484.83      , 264543.7       ,
       140454.63      , 187240.5       ,  96302.36      ,  90449.        ,
       116671.65      , 148360.        , 228855.2       , 135487.4       ,
       157306.37      , 101386.5       , 122446.00666667, 161137.72      ,
       102318.38      , 192607.1       , 227835.6       , 221014.1       ,
       165516.        , 130722.93333333, 169068.35333333, 181428.71      ,
       111241.75      , 183843.77      , 158830.        , 256614.09      ,
        92399.        , 365464.58      , 211098.76      , 282664.31      ,
        99619.5       , 231846.49      , 397665.9       , 439364.21      ,
       151554.84285714, 160253.75      , 179645.7       , 125330.41      ,
       397478.64      , 306615.76      , 237716.7       ,  73938.11      ,
       176662.        , 317681.28      , 145186.7       , 197625.79      ,
       134639.26      , 206057.4       , 128616.25      , 230918.03      ,
       206480.        , 165175.        , 226480.        , 109954.5       ,
       125251.5       , 377913.98      , 165355.09      , 126191.22      ,
       205070.18      , 210363.        ,  99210.        , 267722.28      ,
       462169.76      , 199692.        ,  84541.        ,  79615.        ,
       343791.98      , 127647.        ,  99110.        , 279388.95      ,
       240676.28      , 183122.82      , 153212.48      , 168050.25      ,
        94732.        , 112098.33      , 191570.95      , 189410.8       ,
       179503.59      , 139991.5       , 136510.07      , 194860.32      ,
       167139.55      , 179168.3       , 112354.86      , 158862.38      ,
       148653.        ,  99034.12      , 117006.34      , 141965.        ,
       282770.44      , 132943.25      , 181425.95      , 184717.        ,
       108882.75      , 256528.39      ,  90583.93      , 245153.5       ,
       122780.62      , 235954.49      , 123126.        , 362755.28      ,
       176199.        , 142114.75      , 123545.        , 238182.1       ,
       155936.14      , 181617.71      , 167041.        , 154108.        ,
       125093.75      , 175416.9       , 125902.66      , 139591.5       ,
       277336.89      , 162038.        , 156857.75      , 228064.        ,
       165082.        , 149275.6       ,  97379.04      , 112874.3       ,
       109440.        , 123608.875     , 205051.54      , 316789.42      ,
       124286.25      , 126066.5       , 164904.18      , 383300.87      ,
       301332.99      , 162123.93      , 265253.43      , 221648.54      ,
       277070.9       , 186080.        , 205056.6       , 245163.89      ,
        83954.28      , 148559.16      , 174093.7       , 128285.43      ,
       240783.2       , 159089.        , 407825.5       , 107922.04      ,
       153988.        , 142335.        , 151149.18666667,  81660.        ,
       204294.        , 264220.44      , 115472.49      , 255315.28      ,
       138283.25      , 108225.        , 143882.5       , 112984.        ,
       122035.625     , 111074.75      , 153892.5       , 180899.37      ,
       257581.04      , 394159.21      ,  96927.        , 117739.16      ,
       210156.        ,  71301.44      , 142971.75      , 178273.5       ,
       133406.5       , 173075.52      , 169071.        , 180396.2       ,
       327350.33      , 220100.02      , 168036.43      ,  89649.        ,
       128951.        , 289545.07      , 113127.51      , 364341.34      ,
       252366.75      , 247768.36      , 160907.        , 114090.        ,
       177568.7       , 128181.38      , 140792.5       , 108412.62      ,
       199517.11      ,  92745.        , 269145.22      , 124232.22      ,
       299462.5       , 333250.01      , 119214.5       , 146318.        ,
       141834.99      , 116235.83      , 230523.        , 120015.61      ,
       230827.85      , 133254.5       , 150073.5       , 211727.46      ,
       144407.5       , 177636.        , 163631.        , 280873.68      ,
       229920.02      , 442536.16      ])

In [72]:
rf_mae = mean_absolute_error(y_test,rf_predict)
rf_mae

23175.58262970211

In [46]:
te = pd.read_csv('C:/Users/Nikhil/Downloads/test.csv')
te

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [11]:
tr = pd.read_csv('C:/Users/Nikhil/Downloads/train.csv',index_col='Id')
tr

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [12]:
z = te[['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']]

In [52]:
model_1 = RandomForestRegressor(n_estimators=50, random_state=0)
model_2 = RandomForestRegressor(n_estimators=100, random_state=0)
model_3 = RandomForestRegressor(n_estimators=150, random_state=0)
model_4 = RandomForestRegressor(n_estimators=200, min_samples_split=20, random_state=0)
model_5 = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=0)

model = [model_1,model_2,model_3,model_4,model_5]

In [53]:
MAE2 = []
for i in model:
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
    i.fit(x_train,y_train)
    preds_val = i.predict(x_test)
    MAE3 = mean_absolute_error(y_test,preds_val)
    MAE2.append(MAE3)

In [54]:
MAE2

[24015.492818003917,
 23740.979228636657,
 23752.723268101763,
 23996.676789668687,
 23706.672864217904]

In [55]:
my_model = model_2

In [56]:
my_model.fit(x,y)

RandomForestRegressor(random_state=0)

In [58]:
predict_test = my_model.predict(z)
predict_test

array([121501.  , 154652.  , 182625.  , ..., 160942.02, 127412.  ,
       223235.35])

# Missing Values

In [65]:
tr.isna().sum()

MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
Street             0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 80, dtype: int64

In [74]:
b = tr.dropna(axis=0,subset=['SalePrice'])

In [77]:
x1 = b.drop('SalePrice',axis=1)
y1 = b[['SalePrice']]

In [78]:
x2 = b.select_dtypes(exclude=['object'])
z2 =te.select_dtypes(exclude=['object'])

In [85]:
x_train,x_test,y_train,y_test = train_test_split(x2,y1,test_size=0.2,random_state=0)

In [86]:
x_train.shape

(1168, 37)

In [90]:
missing_value_count = x_train.isna().sum()

In [102]:
missed = missing_value_count[missing_value_count > 0]
missed

LotFrontage    212
MasVnrArea       6
GarageYrBlt     58
dtype: int64

In [97]:
row = x_train.shape[0]
row

1168

In [103]:
missed.count()

3

In [104]:
missed.sum()

276

In [109]:
reduced_X_train = x_train.dropna(axis=1)
reduced_X_train

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
619,20,11694,9,5,2007,2007,48,0,1774,1822,...,0,108,0,0,260,0,0,7,2007,314813
871,20,6600,5,5,1962,1962,0,0,894,894,...,0,0,0,0,0,0,0,8,2009,109500
93,30,13360,5,7,1921,2006,713,0,163,876,...,0,0,44,0,0,0,0,8,2009,163500
818,20,13265,8,5,2002,2002,1218,0,350,1568,...,150,59,0,0,0,0,0,7,2008,271000
303,20,13704,7,5,2001,2002,0,0,1541,1541,...,468,81,0,0,0,0,0,1,2006,205000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764,60,9430,8,5,1999,1999,1163,0,89,1252,...,0,128,0,0,180,0,0,7,2009,337000
836,20,9600,4,7,1950,1995,442,0,625,1067,...,290,0,0,0,0,0,0,2,2010,128000
1217,90,8930,6,5,1978,1978,0,0,0,0,...,0,0,0,0,0,0,0,4,2010,112000
560,120,3196,7,5,2003,2004,0,0,1374,1374,...,143,20,0,0,0,0,0,10,2006,234000
685,60,16770,7,5,1998,1998,0,0,1195,1195,...,0,81,0,0,0,0,0,6,2010,221000

In [112]:
reduced_X_test = x_test.dropna(axis=1)
reduced_X_test

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
530,20,32668,6,3,1957,1975,1219,0,816,2035,...,0,0,200,0,0,0,0,3,2007,200624
492,50,9490,6,7,1941,1950,403,165,238,806,...,0,0,32,0,0,0,0,8,2006,133000
460,50,7015,5,4,1950,1950,185,0,524,709,...,0,0,248,0,0,0,0,7,2009,110000
280,60,10005,7,5,1977,1977,392,0,768,1160,...,288,117,0,0,0,0,0,3,2008,192000
656,160,1680,6,5,1971,1971,0,0,525,525,...,0,0,0,0,0,0,0,3,2010,88000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,120,10846,8,5,1993,1993,1619,0,100,1719,...,122,30,0,0,0,0,0,5,2008,324000
441,20,15431,10,5,2008,2008,1767,539,788,3094,...,0,72,0,0,170,0,0,4,2009,555000
1388,50,8520,6,7,1916,1950,168,546,0,714,...,88,15,0,0,0,0,0,8,2007,136000
1324,30,5330,4,7,1940,1950,280,0,140,420,...,164,0,0,0,0,0,0,12,2009,82500
62,75,7200,5,7,1920,1996,0,0,530,530,...,0,0,144,0,0,0,0,3,2007,101000

In [116]:
model = RandomForestRegressor(n_estimators=100, random_state=0)

In [117]:
model.fit(reduced_X_train,y_train)

RandomForestRegressor(random_state=0)

In [118]:
preds = model.predict(reduced_X_test)
preds

array([200749.92, 132999.  , 110018.  , 192246.6 ,  87875.  ,  84942.  ,
       283817.99, 141217.  , 646458.4 , 149005.  , 208918.  , 136930.5 ,
       224904.  , 122974.  , 118950.58, 144974.  , 189999.5 , 123790.  ,
       149423.  , 155027.45, 165722.3 , 144405.1 , 110010.5 , 173956.99,
       185010.  , 168006.4 , 177301.45,  84632.  , 319197.72, 118420.64,
       109926.88, 213155.  , 155873.89, 250182.7 , 374014.51, 174976.18,
       276972.  , 112222.5 , 263024.17, 326068.32, 242117.28, 129982.  ,
       164976.  , 280079.82, 402543.71, 118930.98, 124984.  , 128045.  ,
       172466.7 ,  84761.  , 404454.34, 155890.85, 167880.  , 100004.76,
       274955.05, 122874.  , 131963.5 , 239941.86, 138974.87, 114995.04,
       137535.5 , 135000.  , 134441.34, 180557.34, 192974.  , 156657.85,
       131995.5 , 224610.  , 138929.53, 224966.  , 188497.  , 117990.  ,
        81400.  , 394175.61, 112055.  , 248617.86, 134537.2 ,  79949.  ,
       319079.11, 157942.  , 139982.5 , 136594.9 , 107458.8 , 145017.  ,
       200149.89, 185031.5 , 105150.04, 202542.41, 185880.  , 135863.7 ,
       200089.2 , 189988.  , 187522.  , 200019.41, 172324.13, 157044.28,
       213117.  , 185023.5 , 124487.  , 163094.9 , 259815.8 , 198332.82,
       119952.  , 159435.44, 105751.  , 259875.75, 143043.  , 106038.  ,
       178947.45, 126966.75,  89782.  , 118423.48, 189989.5 , 120017.5 ,
       183765.  , 155030.05, 384446.71, 132954.  , 193012.  , 269704.89,
       141054.25, 146069.  , 128597.  , 176063.73, 213852.  , 221874.  ,
       415979.68, 187440.  , 199949.97, 179996.  , 205937.5 , 194303.  ,
       143021.  , 183322.68, 116127.  , 213051.  , 139405.37, 179071.6 ,
       107995.48, 176009.85, 158547.2 , 145067.02, 217023.1 , 150830.  ,
       108845.  , 165434.  , 200859.61, 145133.5 , 319176.58, 215173.  ,
       180559.34, 371411.75, 239292.82, 145968.  , 161180.84, 249860.4 ,
        89629.  , 229974.  , 146981.  , 163971.1 ,  97003.  , 142061.  ,
       196878.41, 128873.  , 232326.48, 115025.2 , 174993.51, 264290.73,
       207364.5 , 181044.07, 176036.84, 171296.5 , 196104.  , 175984.56,
       112722.5 , 138918.22, 134984.  , 239876.81, 111975.  , 133917.24,
       316666.81, 169737.9 , 116087.08, 305647.49,  82609.  , 174927.  ,
       105770.  , 194373.  , 194327.  , 155770.4 , 137959.  , 176932.02,
       213818.  , 148129.  , 126950.  , 142415.25,  79891.  , 145047.02,
       171275.  , 122436.  , 139012.87, 188945.  , 120537.  , 123985.  ,
       160031.44, 199909.1 , 159988.5 , 312101.41, 274947.9 ,  66665.32,
       159025.62, 250084.36,  93300.  , 109530.22, 376902.22, 128833.  ,
        82588.  , 301970.97, 250044.2 ,  80666.  , 187516.5 , 110008.08,
       116807.  , 128640.5 , 213290.  , 284787.91, 229955.  , 190000.  ,
       134991.  , 151963.  ,  87328.  , 155087.8 , 115030.  , 144033.78,
       248302.34, 132448.  , 135887.1 , 116921.  ,  81448.  , 157723.32,
       109957.  , 180971.7 , 192441.4 , 223258.  , 180937.78, 169990.9 ,
       187547.  , 185857.  , 160027.48, 192230.6 , 181646.06, 266127.19,
       100003.76, 442506.75, 229077.85, 216996.2 , 110253.  , 176001.15,
       574935.97, 160007.15, 172482.35, 108007.6 , 131425.  , 105878.  ,
       379418.13, 372340.88, 345146.1 ,  67529.42, 250080.77, 245017.32,
       125023.  , 233538.86, 145000.52, 180914.38, 103362.88, 232741.38,
       163821.5 , 219421.5 , 194987.  , 108055.48, 149911.5 , 314682.69,
       177292.4 , 140000.  , 194397.  , 137858.24, 118045.  , 326448.32,
       599449.46, 135846.9 ,  82408.  , 101376.36])

In [119]:
mean_absolute_error(y_test,preds)

909.0415068493146

In [120]:
from sklearn.impute import SimpleImputer

In [121]:
si = SimpleImputer()

In [127]:
x_train['LotFrontage'] = x_train['LotFrontage'].fillna(x_train['LotFrontage'].mean())

In [128]:
x_train['MasVnrArea'] = x_train['MasVnrArea'].fillna(x_train['MasVnrArea'].mean())

In [129]:
x_train['GarageYrBlt'] = x_train['GarageYrBlt'].fillna(x_train['GarageYrBlt'].mean())

In [136]:
test_miss = x_test.isna().sum()
test_miss[test_miss > 0]

LotFrontage    47
MasVnrArea      2
GarageYrBlt    23
dtype: int64

# Categorical Variables

In [140]:
X = x2.dropna(axis=1)

In [152]:
tr

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [144]:
y1

      SalePrice
Id
1        208500
2        181500
3        223500
4        140000
5        250000
...         ...
1456     175000
1457     210000
1458     266500
1459     142125
1460     147500

[1460 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x = tr.drop('SalePrice',axis=1)
y=tr[['SalePrice']]

In [8]:
x1 = x.select_dtypes(exclude='object')
x1_test = te.select_dtypes(exclude='object')

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x1,y,test_size=0.2,random_state=0)

In [10]:
x_train.shape

(1168, 37)

In [16]:
missed = x_train.isna().sum()

In [26]:
missing_values = missed[missed > 0]
missing_values

LotFrontage    212
MasVnrArea       6
GarageYrBlt     58
dtype: int64

In [19]:
missing_values.sum()

276

In [36]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [29]:
def score_dataset(x_train,x_test, y_train, y_test):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(x_train, y_train)
    preds = model.predict(x_test)
    return mean_absolute_error(y_test, preds)

In [36]:
# MAE Value by dropping missing values column
reduced_x_train = x_train.dropna(axis=1)

In [33]:
reduced_x_test = x_test.dropna(axis=1)

In [35]:
print('MAE:',score_dataset(reduced_x_train,reduced_x_test,y_train,y_test))

MAE: 17952.591404109586

In [37]:
from sklearn.impute import SimpleImputer

In [38]:
si = SimpleImputer()

In [48]:
# MAE value by implementing simpleImputer 
imputed_x_train = pd.DataFrame(si.fit_transform(x_train))
imputed_x_train

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,619.0,20.0,90.000000,11694.0,9.0,5.0,2007.0,2007.0,452.0,48.0,...,774.0,0.0,108.0,0.0,0.0,260.0,0.0,0.0,7.0,2007.0
1,871.0,20.0,60.000000,6600.0,5.0,5.0,1962.0,1962.0,0.0,0.0,...,308.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,2009.0
2,93.0,30.0,80.000000,13360.0,5.0,7.0,1921.0,2006.0,0.0,713.0,...,432.0,0.0,0.0,44.0,0.0,0.0,0.0,0.0,8.0,2009.0
3,818.0,20.0,69.614017,13265.0,8.0,5.0,2002.0,2002.0,148.0,1218.0,...,857.0,150.0,59.0,0.0,0.0,0.0,0.0,0.0,7.0,2008.0
4,303.0,20.0,118.000000,13704.0,7.0,5.0,2001.0,2002.0,150.0,0.0,...,843.0,468.0,81.0,0.0,0.0,0.0,0.0,0.0,1.0,2006.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,764.0,60.0,82.000000,9430.0,8.0,5.0,1999.0,1999.0,673.0,1163.0,...,856.0,0.0,128.0,0.0,0.0,180.0,0.0,0.0,7.0,2009.0
1164,836.0,20.0,60.000000,9600.0,4.0,7.0,1950.0,1995.0,0.0,442.0,...,436.0,290.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2010.0
1165,1217.0,90.0,68.000000,8930.0,6.0,5.0,1978.0,1978.0,0.0,0.0,...,539.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2010.0
1166,560.0,120.0,69.614017,3196.0,7.0,5.0,2003.0,2004.0,18.0,0.0,...,420.0,143.0,20.0,0.0,0.0,0.0,0.0,0.0,10.0,2006.0
1167,685.0,60.0,58.000000,16770.0,7.0,5.0,1998.0,1998.0,30.0,0.0,...,486.0,0.0,81.0,0.0,0.0,0.0,0.0,0.0,6.0,2010.0

In [50]:
imputed_x_test = pd.DataFrame(si.transform(x_test))
imputed_x_test

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,530.0,20.0,69.614017,32668.0,6.0,3.0,1957.0,1975.0,103.481067,1219.0,...,484.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,3.0,2007.0
1,492.0,50.0,79.000000,9490.0,6.0,7.0,1941.0,1950.0,0.000000,403.0,...,240.0,0.0,0.0,32.0,0.0,0.0,0.0,0.0,8.0,2006.0
2,460.0,50.0,69.614017,7015.0,5.0,4.0,1950.0,1950.0,161.000000,185.0,...,352.0,0.0,0.0,248.0,0.0,0.0,0.0,0.0,7.0,2009.0
3,280.0,60.0,83.000000,10005.0,7.0,5.0,1977.0,1977.0,299.000000,392.0,...,505.0,288.0,117.0,0.0,0.0,0.0,0.0,0.0,3.0,2008.0
4,656.0,160.0,21.000000,1680.0,6.0,5.0,1971.0,1971.0,381.000000,0.0,...,264.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,327.0,120.0,32.000000,10846.0,8.0,5.0,1993.0,1993.0,0.000000,1619.0,...,473.0,122.0,30.0,0.0,0.0,0.0,0.0,0.0,5.0,2008.0
288,441.0,20.0,105.000000,15431.0,10.0,5.0,2008.0,2008.0,200.000000,1767.0,...,672.0,0.0,72.0,0.0,0.0,170.0,0.0,0.0,4.0,2009.0
289,1388.0,50.0,60.000000,8520.0,6.0,7.0,1916.0,1950.0,0.000000,168.0,...,216.0,88.0,15.0,0.0,0.0,0.0,0.0,0.0,8.0,2007.0
290,1324.0,30.0,50.000000,5330.0,4.0,7.0,1940.0,1950.0,0.000000,280.0,...,0.0,164.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,2009.0
291,62.0,75.0,60.000000,7200.0,5.0,7.0,1920.0,1996.0,0.000000,0.0,...,288.0,0.0,0.0,144.0,0.0,0.0,0.0,0.0,3.0,2007.0

In [51]:
imputed_x_train.columns = x_train.columns
imputed_x_test.columns = x_test.columns

In [53]:
print('MAE-Imputed:',score_dataset(imputed_x_train,imputed_x_test,y_train,y_test))

MAE-Imputed: 18250.608013698627

In [99]:
l = missing_values.reset_index()['index'].unique()
l.tolist()

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [87]:
x_train_plus = x_train.copy
x_test_plus = x_test.copy

In [105]:
for col in l.tolist():
    p = x_train_plus[col].isnull()
    x_train_plus[col + 'missing'] = p

TypeError: 'method' object is not subscriptable

In [93]:
cols_with_missing = [col for col in x_train.columns
                     if x_train[col].isnull().any()]

In [94]:
cols_with_missing

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

# Categorical Variable

In [5]:
X = x.dropna(axis=1)

In [9]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [113]:
x_train['Condition2'].unique()

array(['Norm', 'PosA', 'Feedr', 'PosN', 'Artery', 'RRAe'], dtype=object)

In [122]:
object_col = x_train.select_dtypes(include='object').columns
object_cols = object_col.tolist()
object_cols

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'KitchenQual',
 'Functional',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [120]:
good_label_cols = [col for col in object_cols if 
                   set(x_test[col]).issubset(set(x_train[col]))]

In [121]:
good_label_cols

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'Exterior1st',
 'Exterior2nd',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'KitchenQual',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [126]:
set(x_test['Street']).issubset(set(x_train['Street']))

True

In [127]:
bad_label_cols = list(set(object_cols)-set(good_label_cols))

In [128]:
bad_label_cols

['Functional', 'RoofMatl', 'Condition2']

In [129]:
label_x_train = x_train.drop(bad_label_cols,axis=1)
label_x_test = x_test.drop(bad_label_cols, axis=1)

In [142]:
label_x_train

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
618,619,20,RL,11694,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,108,0,0,260,0,0,7,2007,New,Partial
870,871,20,RL,6600,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,0,8,2009,WD,Normal
92,93,30,RL,13360,Pave,IR1,HLS,AllPub,Inside,Gtl,...,0,44,0,0,0,0,8,2009,WD,Normal
817,818,20,RL,13265,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,...,59,0,0,0,0,0,7,2008,WD,Normal
302,303,20,RL,13704,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,81,0,0,0,0,0,1,2006,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,764,60,RL,9430,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,128,0,0,180,0,0,7,2009,WD,Normal
835,836,20,RL,9600,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,0,2,2010,WD,Normal
1216,1217,90,RM,8930,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,0,4,2010,WD,Normal
559,560,120,RL,3196,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,20,0,0,0,0,0,10,2006,WD,Normal
684,685,60,RL,16770,Pave,IR2,Lvl,AllPub,CulDSac,Gtl,...,81,0,0,0,0,0,6,2010,WD,Normal

In [132]:
from sklearn.preprocessing import OrdinalEncoder

In [134]:
ol = OrdinalEncoder()

In [148]:
label_x_train[good_label_cols] = ol.fit_transform(label_x_train[good_label_cols])

In [149]:
label_x_train

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
618,619,20,3.0,11694,1.0,3.0,3.0,0.0,4.0,0.0,...,108,0,0,260,0,0,7,2007,6.0,5.0
870,871,20,3.0,6600,1.0,3.0,3.0,0.0,4.0,0.0,...,0,0,0,0,0,0,8,2009,8.0,4.0
92,93,30,3.0,13360,1.0,0.0,1.0,0.0,4.0,0.0,...,0,44,0,0,0,0,8,2009,8.0,4.0
817,818,20,3.0,13265,1.0,0.0,3.0,0.0,1.0,0.0,...,59,0,0,0,0,0,7,2008,8.0,4.0
302,303,20,3.0,13704,1.0,0.0,3.0,0.0,0.0,0.0,...,81,0,0,0,0,0,1,2006,8.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,764,60,3.0,9430,1.0,3.0,3.0,0.0,4.0,0.0,...,128,0,0,180,0,0,7,2009,8.0,4.0
835,836,20,3.0,9600,1.0,3.0,3.0,0.0,4.0,0.0,...,0,0,0,0,0,0,2,2010,8.0,4.0
1216,1217,90,4.0,8930,1.0,3.0,3.0,0.0,4.0,0.0,...,0,0,0,0,0,0,4,2010,8.0,4.0
559,560,120,3.0,3196,1.0,3.0,3.0,0.0,4.0,0.0,...,20,0,0,0,0,0,10,2006,8.0,4.0
684,685,60,3.0,16770,1.0,1.0,3.0,0.0,1.0,0.0,...,81,0,0,0,0,0,6,2010,8.0,4.0

In [150]:
label_x_test[good_label_cols] = ol.transform(label_x_test[good_label_cols])

In [151]:
label_x_test

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
529,530,20,3.0,32668,1.0,0.0,3.0,0.0,1.0,0.0,...,0,200,0,0,0,0,3,2007,8.0,2.0
491,492,50,3.0,9490,1.0,3.0,3.0,0.0,4.0,0.0,...,0,32,0,0,0,0,8,2006,8.0,4.0
459,460,50,3.0,7015,1.0,0.0,0.0,0.0,0.0,0.0,...,0,248,0,0,0,0,7,2009,8.0,4.0
279,280,60,3.0,10005,1.0,3.0,3.0,0.0,4.0,0.0,...,117,0,0,0,0,0,3,2008,8.0,4.0
655,656,160,4.0,1680,1.0,3.0,3.0,0.0,4.0,0.0,...,0,0,0,0,0,0,3,2010,8.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,327,120,3.0,10846,1.0,0.0,3.0,0.0,1.0,0.0,...,30,0,0,0,0,0,5,2008,2.0,4.0
440,441,20,3.0,15431,1.0,3.0,3.0,0.0,4.0,0.0,...,72,0,0,170,0,0,4,2009,8.0,4.0
1387,1388,50,4.0,8520,1.0,3.0,3.0,0.0,4.0,0.0,...,15,0,0,0,0,0,8,2007,1.0,3.0
1323,1324,30,3.0,5330,1.0,3.0,1.0,0.0,4.0,0.0,...,0,0,0,0,0,0,12,2009,8.0,4.0
61,62,75,4.0,7200,1.0,3.0,3.0,0.0,4.0,0.0,...,0,144,0,0,0,0,3,2007,8.0,4.0

In [153]:
print('MAE-ordinal_encoding:',score_dataset(label_x_train,label_x_test,y_train,y_test))

MAE-ordinal_encoding: 17251.037739726027

In [289]:
low_cardinality_cols = []
for i in object_cols:
    h = x_train[i].unique().size
    if h < 10:
        low_cardinality_cols.append(i)

In [198]:
low_cardinality_cols

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'KitchenQual',
 'Functional',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [203]:
high_cardinality_cols = list(set(object_cols)-set(low_cardinality_cols))
high_cardinality_cols

['Exterior2nd', 'Exterior1st', 'Neighborhood']

In [204]:
from sklearn.preprocessing import OneHotEncoder

In [205]:
oh = OneHotEncoder(handle_unknown='ignore', sparse=False)

In [236]:
oh_x_train = pd.DataFrame(oh.fit_transform(x_train[low_cardinality_cols]))
oh_x_test = pd.DataFrame(oh.transform(x_test[low_cardinality_cols]))

In [238]:
oh_x_train.index = x_train.index

In [239]:
oh_x_test.index = x_test.index

In [241]:
num_x_train = x_train.drop(object_cols,axis=1)
num_x_test = x_test.drop(object_cols,axis=1)

In [242]:
OH_x_train = pd.concat([num_x_train,oh_x_train],axis=1)

In [243]:
OH_x_test = pd.concat([num_x_test,oh_x_test])

In [249]:
OH_x_train1 = OH_x_train.fillna(0)
OH_x_test2 = OH_x_test.fillna(0)

In [251]:
OH_x_train1.shape

(1168, 156)

In [252]:
OH_x_test2.shape

(584, 156)

In [254]:
y_test.shape

(292, 1)

In [250]:
print('MAE-Onehotencoding:',score_dataset(OH_x_train1,OH_x_test2,y_train,y_test))

ValueError: Found input variables with inconsistent numbers of samples: [292, 584]

# Pipelines

In [294]:
x_train_num = x_train.select_dtypes('int64','float64')

In [296]:
x_train_num1

['Id',
 'MSSubClass',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [292]:
cat_x_train = low_cardinality_cols.copy()
cat_x_train

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'KitchenQual',
 'Functional',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [297]:
my_cols = cat_x_train + x_train_num1

In [18]:
catagorical_col = [cname for cname in x_train.columns if x_train[cname].nunique() < 10 and x_train[cname].dtype=='object' ]
catagorical_col

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'KitchenQual',
 'Functional',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [19]:
numerical_col = [cname for cname in x_train.columns if x_train[cname].dtype in ['int64','float32']]
numerical_col

['Id',
 'MSSubClass',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [17]:
my_col = catagorical_col + numerical_col

In [22]:
x_train1 = x_train[my_col].copy()
x_test1 = x_test[my_col].copy()

In [23]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [31]:
num_pre = SimpleImputer(strategy='constant')

In [30]:
cat_pre = Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('onehot',OneHotEncoder(handle_unknown='ignore'))])

In [33]:
preprocessor = ColumnTransformer(transformers=[('num',num_pre,numerical_col),('cat',cat_pre,catagorical_col)])

In [37]:
model = RandomForestRegressor(n_estimators=100, random_state=0)

In [40]:
my_pipeline = Pipeline(steps=[('preprocessor',preprocessor),('model',model)])

In [41]:
my_pipeline.fit(x_train1,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='constant'),
                                                  ['Id', 'MSSubClass',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', '1stFlrSF',
                                                   '2ndFlrSF', 'LowQualFinSF',
                                                   'GrLivArea', 'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBath',
                                                   'HalfBath', 'Bedroo...
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['MSZoning', 'Street',
                                                   'LotShape', 'LandContour',
                                                   'Utilities', 'LotConfig',
                                                   'LandSlope', 'Condition1',
                                                   'Condition2', 'BldgType',
                                                   'HouseStyle', 'RoofStyle',
                                                   'RoofMatl', 'ExterQual',
                                                   'ExterCond', 'Foundation',
                                                   'Heating', 'HeatingQC',
                                                   'CentralAir', 'KitchenQual',
                                                   'Functional', 'PavedDrive',
                                                   'SaleType',
                                                   'SaleCondition'])])),
                ('model', RandomForestRegressor(random_state=0))])

In [42]:
preds = my_pipeline.predict(x_test1)

In [44]:
mean_absolute_error(y_test,preds)

17514.224246575344

# Cross Validation

In [51]:
X1 =X[numerical_col].copy()

In [54]:
my_pipeline1 = Pipeline(steps=[('preprocessor',SimpleImputer()),('model',RandomForestRegressor(n_estimators=50, random_state=0))])

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
scores = -1*cross_val_score(my_pipeline1,X1,y,cv=5,scoring='neg_mean_absolute_error')

In [58]:
scores.mean()

18223.716246575343

In [60]:
def get_score(n_estimatores):
    my_pipeline1 = Pipeline(steps=[('preprocessor',SimpleImputer()),('model',RandomForestRegressor(n_estimators=n_estimatores, random_state=0))])
    scores = -1*cross_val_score(my_pipeline1,X1,y,cv=5,scoring='neg_mean_absolute_error')
    return scores.mean()

In [62]:
get_score(150)

17897.405739726026

In [ ]:
# Data